// AUTO-GENERATED by scripts/sync-player-photos.js — do not edit by hand.
// Maps each player name to its LOCAL photo path under public/images/players/.
// Photos load from local files only — no external URLs at runtime.
// If a file is absent, <PlayerCard> falls back to a generated avatar, then initials.

export const PLAYER_IMAGES: Record<string, string> = {
  "Virat Kohli": "/images/players/virat-kohli.jpg",
  "AB de Villiers": "/images/players/ab-de-villiers.jpg",
  "MS Dhoni": "/images/players/ms-dhoni.jpg",
  "Rohit Sharma": "/images/players/rohit-sharma.jpg",
  "Jasprit Bumrah": "/images/players/jasprit-bumrah.jpg",
  "Shakib Al Hasan": "/images/players/shakib-al-hasan.jpg",
  "Lasith Malinga": "/images/players/lasith-malinga.jpg",
  "Rashid Khan": "/images/players/rashid-khan.jpg",
  "Chris Gayle": "/images/players/chris-gayle.jpg",
  "Brendon McCullum": "/images/players/brendon-mccullum.jpg",
  "Shane Watson": "/images/players/shane-watson.jpg",
  "Glenn Maxwell": "/images/players/glenn-maxwell.jpg",
  "David Warner": "/images/players/david-warner.jpg",
  "Dale Steyn": "/images/players/dale-steyn.jpg",
  "Daniel Vettori": "/images/players/daniel-vettori.jpg",
  "Martin Guptill": "/images/players/martin-guptill.jpg",
  "KL Rahul": "/images/players/kl-rahul.jpg",
  "Hardik Pandya": "/images/players/hardik-pandya.jpg",
  "Suryakumar Yadav": "/images/players/suryakumar-yadav.jpg",
  "Rishabh Pant": "/images/players/rishabh-pant.jpg",
  "Ravindra Jadeja": "/images/players/ravindra-jadeja.jpg",
  "Shubman Gill": "/images/players/shubman-gill.jpg",
  "Shreyas Iyer": "/images/players/shreyas-iyer.jpg",
  "Yuzvendra Chahal": "/images/players/yuzvendra-chahal.jpg",
  "Mohammed Shami": "/images/players/mohammed-shami.jpg",
  "Trent Boult": "/images/players/trent-boult.jpg",
  "Pat Cummins": "/images/players/pat-cummins.jpg",
  "Faf du Plessis": "/images/players/faf-du-plessis.jpg",
  "Quinton de Kock": "/images/players/quinton-de-kock.jpg",
  "Kagiso Rabada": "/images/players/kagiso-rabada.jpg",
  "Jos Buttler": "/images/players/jos-buttler.jpg",
  "Ben Stokes": "/images/players/ben-stokes.jpg",
  "Sam Curran": "/images/players/sam-curran.jpg",
  "Liam Livingstone": "/images/players/liam-livingstone.jpg",
  "Nicholas Pooran": "/images/players/nicholas-pooran.jpg",
  "Andre Russell": "/images/players/andre-russell.jpg",
  "Sunil Narine": "/images/players/sunil-narine.jpg",
  "Tilak Varma": "/images/players/tilak-varma.jpg",
  "Rinku Singh": "/images/players/rinku-singh.jpg",
  "Yashasvi Jaiswal": "/images/players/yashasvi-jaiswal.jpg",
  "Prabhsimran Singh": "/images/players/prabhsimran-singh.jpg",
  "Arshdeep Singh": "/images/players/arshdeep-singh.jpg",
  "Mukesh Kumar": "/images/players/mukesh-kumar.jpg",
  "Avesh Khan": "/images/players/avesh-khan.jpg",
  "Deepak Chahar": "/images/players/deepak-chahar.jpg",
  "Shivam Dube": "/images/players/shivam-dube.jpg",
  "Rahul Tewatia": "/images/players/rahul-tewatia.jpg",
  "Axar Patel": "/images/players/axar-patel.jpg",
  "Washington Sundar": "/images/players/washington-sundar.jpg",
  "Sai Sudharsan": "/images/players/sai-sudharsan.jpg",
  "Abhishek Sharma": "/images/players/abhishek-sharma.jpg",
  "Ravi Bishnoi": "/images/players/ravi-bishnoi.jpg",
  "Kuldeep Yadav": "/images/players/kuldeep-yadav.jpg",
  "Umran Malik": "/images/players/umran-malik.jpg",
  "Nitish Kumar Reddy": "/images/players/nitish-kumar-reddy.jpg",
  "Harshit Rana": "/images/players/harshit-rana.jpg",
  "Varun Chakravarthy": "/images/players/varun-chakravarthy.jpg",
};

/** Filename-safe slug, e.g. "AB de Villiers" -> "ab-de-villiers". Mirrors the sync script. */
export function playerSlug(name: string): string {
  return name
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

/** Resolve a player's local photo path. Returns the mapped path or a slug-derived default. */
export function getPlayerImage(name: string): string {
  return PLAYER_IMAGES[name] ?? `/images/players/${playerSlug(name)}.jpg`;
}
